saves_path: ~/.minecraft/saves/
world: New World

pdf_save_location:

window_scale: 1

contour_interval: 1
contour_offset: 0
index: 5

smoothen: yes
smoothness: 1

surface_blocks:
  - grass_block
  - grass_path
  - dirt
  - coarse_dirt
  - farmland

  - sand
  - sandstone

  - red_sand
  - red_sandstone

  - clay

  - podzol
  - mycelium

  - stone
  - granite
  - diorite
  - andesite
  - gravel

  - coal_ore
  - iron_ore
  - gold_ore

  - water
